name: Repo Language

on: [pull_request]

jobs:
  run:
    name: Check the repo language
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to checkout all branches for this Action to work

      - uses: dcarbone/install-jq-action@v2

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@v2.4.0
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"

      - name: Changed lines on README.md
        id: changed-lines
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: |
          CHANGED_LINES=$(jq -r '.files[] | select(.path == "README.md" and .type == "ChangedFile").chunks[].changes[] | select(.type != "UnchangedLine").content' $DIFF)
          echo "changed-lines=$CHANGED_LINES" >> "$GITHUB_OUTPUT"

      - name: Get repo URL
        id: repo-url
        run: grep -Po 'https?:\/\/[^\s)]+' <<<"$LINES_DIFF"
        env:
          LINES_DIFF: ${{ steps.changed-lines.outputs.changed-lines }}

      - name: Extracting Repo Languages
        id: langsDetector
        run: |
          REPO_LANGUAGES=`curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/languages \
          | jq -c 'keys|tostring'`

          echo "REPO_LANGUAGES=$REPO_LANGUAGES" >> "$GITHUB_OUTPUT"
          echo "Repo languages are $REPO_LANGUAGES"
