name: Template Validator

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened]

jobs:
  template_validator:
    runs-on: ubuntu-latest
    name: Template Validator
    steps:
      - name: All Checks
        uses: ranemihir/template-validator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue--greeting-message: "Thanks for your contribution! :)"
          pull-request--greeting-message: "Thanks for your contribution! :)"
